apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: sharmahm
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: finance_password
  MYSQL_DATABASE: finance_app
  MYSQL_USER: finance_user
  MYSQL_PASSWORD: finance_password
